scopes:
	cue eval scopes.cue

selectors:
	cue eval selectors.cue

alias:
	cue eval alias.cue

emit:
	cue eval emit.cue

cycle:
	cue eval cycle.cue

cycleref:
	cue eval cycleref.cue

hidden:
	cue export hidden.cue
