json:
	cue export json.cue

dup:
	cue eval dup.cue

check:
	cue eval check.cue

schema:
	cue export schema.cue

validation:
	cue vet validation.cue data.yaml

order:
	cue eval -i order.cue

fold:
	cue export fold.cue
