op:
	cue eval -i op.cue

interpolation:
	cue eval interpolation.cue

genfield:
	cue eval genfield.cue

listcomp:
	cue eval listcomp.cue

fieldcomp:
	cue eval -c fieldcomp.cue

conditional:
	cue eval conditional.cue

regexp:
	cue eval -i regexp.cue

coalesce:
	cue eval coalesce.cue
