types:
	cue eval types.cue

bottom:
	cue eval -E bottom.cue

numbers:
	cue eval -E numbers.cue

stringlit:
	cue export stringlit.cue

stringraw:
	cue eval stringraw.cue

bytes:
	cue export bytes.cue

structs:
	cue eval -E structs.cue

defs:
	cue eval -E defs.cue

structs2:
	cue eval structs2.cue

disjunctions:
	cue eval disjunctions.cue

defaults:
	cue eval defaults.cue

sumstruct:
	cue eval sumstruct.cue

bounds:
	cue eval -E bounds.cue

bounds2:
	cue eval -E bounds2.cue

lists:
	cue eval -E lists.cue

templates:
	cue eval templates.cue
